# Generated by Django 4.2.2 on 2023-06-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('isCorrect', models.BooleanField()),
                ('correctText', models.CharField(max_length=200)),
            ],
        ),
    ]
